import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/home1">Home1</Link>
        </li>
        <li>
          <Link to="/aktivitet">Aktivitet</Link>
        </li>
        <li>
          <Link to="/detailsmultiitem">DetailsMultiItem</Link>
        </li>
        <li>
          <Link to="/detailsitemsbidone">DetailsItemsBidOne</Link>
        </li>
        <li>
          <Link to="/marketplacemenu">MarketplaceMenu</Link>
        </li>
        <li>
          <Link to="/companydetail">CompanyDetail</Link>
        </li>
        <li>
          <Link to="/connectwalletone">ConnectWalletOne</Link>
        </li>
        <li>
          <Link to="/connectwallet">ConnectWallet</Link>
        </li>
        <li>
          <Link to="/detailssingleitem">DetailsSingleItem</Link>
        </li>
        <li>
          <Link to="/detailsitemsbid">DetailsItemsBid</Link>
        </li>
        <li>
          <Link to="/detailsmultiitemone">DetailsMultiItemOne</Link>
        </li>
        <li>
          <Link to="/onlywebsite">Onlywebsite</Link>
        </li>
        <li>
          <Link to="/landingalt">LandingAlt</Link>
        </li>
        <li>
          <Link to="/creatoronclick">CreatorOnclick</Link>
        </li>
        <li>
          <Link to="/ownerpreview">Ownerpreview</Link>
        </li>
        <li>
          <Link to="/changenetwork">ChangeNetwork</Link>
        </li>
        <li>
          <Link to="/hoveraccount">HoverAccount</Link>
        </li>
        <li>
          <Link to="/settings">Settings</Link>
        </li>
        <li>
          <Link to="/message">Message</Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
